version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule: 
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"